Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 33802
"GET / HTTP/1.1" 200 33802
"GET / HTTP/1.1" 200 33802
"GET / HTTP/1.1" 200 33802
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 33802
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2459
"GET / HTTP/1.1" 200 33802
"GET / HTTP/1.1" 200 33802
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Invalid HTTP_HOST header: '192.168.1.28:8000'. You may need to add '192.168.1.28' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/roland/Bureau/SERIES_PROJETS/elk-filebeat-djangoApp/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/roland/Bureau/SERIES_PROJETS/elk-filebeat-djangoApp/venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/roland/Bureau/SERIES_PROJETS/elk-filebeat-djangoApp/venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/roland/Bureau/SERIES_PROJETS/elk-filebeat-djangoApp/venv/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '192.168.1.28:8000'. You may need to add '192.168.1.28' to ALLOWED_HOSTS.
Bad Request: /
"GET / HTTP/1.1" 400 73250
Invalid HTTP_HOST header: '192.168.1.28:8000'. You may need to add '192.168.1.28' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/roland/Bureau/SERIES_PROJETS/elk-filebeat-djangoApp/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/roland/Bureau/SERIES_PROJETS/elk-filebeat-djangoApp/venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/roland/Bureau/SERIES_PROJETS/elk-filebeat-djangoApp/venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/roland/Bureau/SERIES_PROJETS/elk-filebeat-djangoApp/venv/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '192.168.1.28:8000'. You may need to add '192.168.1.28' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
"GET /favicon.ico HTTP/1.1" 400 73073
"GET / HTTP/1.1" 200 33802
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2459
/home/roland/Bureau/SERIES_PROJETS/elk-filebeat-djangoApp/my_django_app/settings.py changed, reloading.
Watching for file changes with StatReloader
